# permissions for end users to edit nifiparameterproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nifiparameterprovider-editor-role
rules:
- apiGroups:
  - nifi.konpyutaika.com
  resources:
  - nifiparameterproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nifi.konpyutaika.com
  resources:
  - nifiparameterproviders/status
  verbs:
  - get
